# Site settings
title: J. Sky Orndoff
email: sky@catanenterprises.com
description: Sky's Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
